# Generated by Django 3.1.7 on 2021-03-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='duration_days',
            field=models.IntegerField(default=5),
        ),
    ]
