# Generated by Django 3.1.7 on 2021-03-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='duration_days',
        ),
    ]
