# Generated by Django 3.1.7 on 2021-03-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_winner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='username', max_length=60),
            preserve_default=False,
        ),
    ]
